In [1]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
import pandas
import numpy
from sklearn.feature_selection import RFE
from sklearn.svm import SVR

# Evaluation Metrics
from sklearn import model_selection
from sklearn.metrics import make_scorer

# Libraries for visuals
import matplotlib.pyplot as plt
import seaborn as sns; sns.set(font_scale=1.2)

# load data
# Read data from .csv and drop the column pID - cocomo341_log, nasa93_log
dataframe = pandas.read_csv('cocomo341_log.csv', header=0).drop(labels='pID', axis=1)

# Feature names
# names = ["LogSIZE","PMAT","PREC","TEAM","FLEX","RESL","PCAP","RELY","CPLX","TIME","STOR","ACAP","PLEX","LTEX","DATA","RUSE","DOCU","PVOL","APEX","PCON","TOOL","SITE","SCED"]
names = numpy.array(dataframe.columns.values)[1:]

# Total number of features
totalFeatureNum = names.size
dataframe

LogPM   LogSIZE      PMAT      PREC      TEAM      FLEX      RESL  \
0    5.049856  4.684813  0.146166  0.232367  0.102597  0.189735  0.132580   
1    9.341369  5.942274  0.463497  0.294737  0.195501  0.301273  0.335738   
2    4.804021  2.624669  0.163779  0.032546  0.000000  0.000000  0.074278   
3    7.620705  4.901341  0.382305  0.243107  0.214679  0.248498  0.346525   
4    6.864848  3.617920  0.225758  0.179449  0.198262  0.183429  0.255787   
5    3.496508  2.772589  0.173010  0.034380  0.030498  0.000000  0.156651   
6    2.079442  1.824549  0.085389  0.000000  0.020070  0.000000  0.077361   
7    8.764053  5.840380  0.455550  0.072421  0.127904  0.177548  0.247632   
8    6.980076  3.413126  0.266224  0.169291  0.187039  0.138232  0.192842   
9    3.713572  2.426218  0.151396  0.000000  0.000000  0.000000  0.034210   
10   7.805882  5.529429  0.345036  0.274260  0.121094  0.223942  0.312413   
11   5.468060  2.708050  0.168982  0.167899  0.118613  0.109676  0.153005   
12   4.043051  2.076061  0.129546  0.025743  0.000000  0.020968  0.058753   
13   7.148346  5.909224  0.414827  0.219823  0.194413  0.179640  0.333871   
14   7.377759  5.549076  0.380889  0.137617  0.121525  0.168692  0.352921   
15   6.968850  3.951244  0.246558  0.146986  0.086532  0.200328  0.111820   
16   2.079442  0.955511  0.059624  0.011848  0.010511  0.009651  0.040514   
17   5.384495  3.413126  0.186357  0.126968  0.074747  0.173045  0.096591   
18   6.405228  3.701302  0.202091  0.137688  0.081059  0.187656  0.104747   
19   8.794825  6.887553  0.429783  0.341623  0.226600  0.349199  0.389147   
20   6.584791  4.705016  0.220195  0.233369  0.103040  0.238544  0.199493   
21   6.259581  4.120012  0.160680  0.204353  0.225777  0.208885  0.291285   
22   5.170484  3.352007  0.209165  0.207824  0.110281  0.135756  0.142125   
23   4.867534  3.218876  0.175751  0.199570  0.105901  0.130364  0.181866   
24   5.958425  4.045154  0.220865  0.250800  0.177178  0.205089  0.228551   
25   1.791759  1.667707  0.078049  0.020680  0.018345  0.016844  0.047196   
26   4.248495  2.950212  0.138070  0.000000  0.032452  0.000000  0.041598   
27   5.493061  4.882802  0.228515  0.121093  0.160644  0.099121  0.207031   
28   5.480639  4.055517  0.316330  0.100577  0.088816  0.123288  0.257931   
29   4.290459  1.272566  0.079408  0.031560  0.027869  0.038686  0.053957   
..        ...       ...       ...       ...       ...       ...       ...   
311  2.626117  1.763017  0.082509  0.065584  0.058003  0.053596  0.074752   
312  2.690565  2.956939  0.138385  0.109998  0.097283  0.089891  0.125374   
313  4.166820  3.989539  0.062237  0.173146  0.087371  0.171750  0.070415   
314  4.344195  4.203797  0.065579  0.182445  0.092063  0.180973  0.074197   
315  3.882594  2.890372  0.000000  0.035841  0.095093  0.087867  0.142929   
316  5.374537  4.420406  0.000000  0.054813  0.145431  0.134380  0.187425   
317  7.368340  6.465865  0.201735  0.160353  0.177165  0.294843  0.182984   
318  4.384524  4.430579  0.138234  0.054939  0.000000  0.179438  0.125385   
319  3.427814  3.337793  0.104139  0.041389  0.073098  0.067757  0.094460   
320  2.415914  2.014903  0.062865  0.049970  0.066290  0.040903  0.085432   
321  4.053349  3.073156  0.000000  0.038107  0.101107  0.093424  0.130302   
322  2.292535  1.944481  0.060668  0.048223  0.063973  0.039473  0.082446   
323  3.672295  1.756914  0.000000  0.043571  0.057802  0.053410  0.099266   
324  4.898287  4.880375  0.076134  0.211808  0.106880  0.210100  0.086139   
325  5.256036  4.725350  0.073715  0.205080  0.103485  0.203426  0.083402   
326  1.667707  2.196113  0.051389  0.027232  0.018118  0.022181  0.030965   
327  1.589235  1.047319  0.049015  0.012987  0.045873  0.042416  0.029639   
328  6.075277  4.984017  0.000000  0.123604  0.163974  0.151514  0.211322   
329  3.144322  2.932881  0.091506  0.036368  0.000000  0.029622  0.083001   
330  3.387952  2.492233  0.000000  0.030904  0.081994  0.075764  0.070530   
331 

In [2]:
array = numpy.array(dataframe.values)
numpy.set_printoptions(precision=5, suppress=True)
array

array([[ 5.04986,  4.68481,  0.14617, ...,  0.08618, -0.15082,  0.     ],
       [ 9.34137,  5.94227,  0.4635 , ...,  0.157  ,  0.     ,  0.13103],
       [ 4.80402,  2.62467,  0.16378, ...,  0.157  ,  0.     ,  0.     ],
       ...,
       [ 3.68492,  3.30512,  0.18046, ..., -0.24846, -0.22314,  0.35767],
       [ 3.90608,  4.19615,  0.19638, ..., -0.10536, -0.07257,  0.13103],
       [ 3.75074,  3.69633,  0.20182, ..., -0.24846, -0.22314,  0.13103]])

In [3]:
# Number of rows
numpy.size(array,0)

341

In [4]:
# Number of columns
numpy.size(array,1)

24

In [5]:
# Features
X = array[:,1:]


In [6]:
# Actual Value
Y = array[:,0]


In [7]:
# Define Scoring Function
def mae_score_func(y, y_pred):
    return numpy.amin(numpy.absolute(1 - numpy.exp(y_pred - y)))



In [8]:
# feature extraction
seed = 7
kfold = model_selection.KFold(n_splits=10, random_state=None)
model = SVR(kernel='linear', C=1000)

best_score = -numpy.inf
best_subset = None
best_fit = None

for n in range(totalFeatureNum, 0, -1):
    rfe = RFE(model, n, step=1)
    fit = rfe.fit(X, Y)
    features = fit.transform(X)
    print(numpy.size(features,1))
    # scoring = 'neg_mean_absolute_error'
    # scoring = 'neg_mean_squared_log_error'   
    scoring = make_scorer(mae_score_func, greater_is_better=False, needs_proba=False)
    results = model_selection.cross_val_score(model, features, Y, cv=kfold, scoring=scoring)

    # print MAE results
    print("MAE for {} feature is {}; Std {}".format(numpy.size(features,1), results.mean(), results.std()))
    if best_score < results.mean():
        best_score = results.mean()
        best_subset = features
        best_fit = fit

23
MAE for 23 feature is -0.014880541239651813; Std 0.015924330199247327
22
MAE for 22 feature is -0.019179039226553563; Std 0.020553529956833225
21
MAE for 21 feature is -0.017694869181858086; Std 0.020279669724850343
20
MAE for 20 feature is -0.020984167533753085; Std 0.021093435904873118
19
MAE for 19 feature is -0.015907291503044884; Std 0.020284820582090538
18
MAE for 18 feature is -0.025571867193487162; Std 0.022396634038882743
17
MAE for 17 feature is -0.011631161129860412; Std 0.01502828958590446
16
MAE for 16 feature is -0.01792768934851362; Std 0.013193980003673202
15
MAE for 15 feature is -0.02301419701297658; Std 0.023913373744754392
14
MAE for 14 feature is -0.017851489232979113; Std 0.021651912358594982
13
MAE for 13 feature is -0.01384520911244943; Std 0.00945259245903579
12
MAE for 12 feature is -0.044917948282608755; Std 0.04604022557672574
11
MAE for 11 feature is -0.0514213476451563; Std 0.03741709874235908
10
MAE for 10 feature is -0.04831268226593351; Std 0.0333227

In [9]:
best_score
#print("Num Features: %d") % fit.n_features_
#fit.n_features_
#print("Selected Features: %s") % fit.support_
#fit.support_
#print("Feature Ranking: %s") % fit.ranking_
#fit.ranking_

-0.011631161129860412

In [10]:
# Num Features
best_fit.n_features_

17

In [11]:
# Selected Features
best_fit.support_

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True])

In [12]:
# Feature Ranking
best_fit.ranking_

array([1, 1, 1, 7, 1, 3, 1, 1, 1, 1, 1, 2, 1, 1, 5, 1, 1, 4, 6, 1, 1, 1,
       1])

In [13]:
# Fit the SVR model
svr_lin = SVR(kernel='linear', C=1000)
y_lin = svr_lin.fit(best_subset, Y).predict(best_subset)

numpy.set_printoptions(precision=5)


In [14]:
best_subset

array([[ 4.68481,  0.14617,  0.23237, ...,  0.08618, -0.15082,  0.     ],
       [ 5.94227,  0.4635 ,  0.29474, ...,  0.157  ,  0.     ,  0.13103],
       [ 2.62467,  0.16378,  0.03255, ...,  0.157  ,  0.     ,  0.     ],
       ...,
       [ 3.30512,  0.18046,  0.08197, ..., -0.24846, -0.22314,  0.35767],
       [ 4.19615,  0.19638,  0.02602, ..., -0.10536, -0.07257,  0.13103],
       [ 3.69633,  0.20182,  0.04583, ..., -0.24846, -0.22314,  0.13103]])

In [15]:
### Linear SVR

In [16]:
# MRE
MRE = 0

for i in range(len(Y)):
    #MRE = MRE + numpy.absolute((Y[i] - y_lin[i])/Y[i])
    #MRE = numpy.absolute(1- numpy.log(numpy.absolute((Y[i] - y_lin[i])/Y[i])))  
    MRE = MRE + numpy.absolute(1- numpy.exp(y_lin[i] - Y[i]))

# MMRE
MMRE = MRE / numpy.size(array, 0)

print(round(MMRE,2))

    

0.44


In [17]:
# PRED
count = 0

MRE = 0


N = 30
for i in range(len(Y)):
    #MRE = numpy.absolute(1- numpy.log(numpy.absolute((Y[i] - y_lin[i])/Y[i])))
    MRE = numpy.absolute(1- numpy.exp(y_lin[i] - Y[i]))

    if MRE <= N/100:
        count = count + 1
 
PRED = 100 * (count / len(Y))

print(round(PRED,2))


55.43


In [18]:
# MAR
Total_AR = 0
for i in range(len(Y)):
    #Total_AR = Total_AR + numpy.absolute(numpy.exp(Y[i] - y_lin[i]))
    Total_AR = Total_AR + numpy.absolute(numpy.exp(Y[i]) - numpy.exp(y_lin[i]))
MAR = Total_AR / numpy.size(array, 0)
print(round(MAR, 2))

174.63


In [19]:
# selected features
for n in range(0, numpy.size(best_fit.support_)):
    if best_fit.support_[n]:
        print(names[n])

LogSIZE
PMAT
PREC
FLEX
PCAP
RELY
CPLX
TIME
STOR
PLEX
LTEX
RUSE
DOCU
PCON
TOOL
SITE
SCED


In [20]:
svr_lin.coef_

array([[ 0.93544,  1.03078,  1.11786,  0.69952,  2.23889,  1.0189 ,
         1.10647,  1.6264 ,  0.76849,  0.90833,  1.45442, -1.36436,
         2.968  ,  0.69904,  0.99482,  1.04591,  1.33021]])